### PR TITLE
Add new board golf2

### PR DESCRIPTION
**Pull request by zmbush**

### CODE REVIEW

**Comment by alevy** [comment]
@zmbush not totally sure what the PR is for. Is it possible this is intended for a different repo?

**Comment by zmbush** [comment]
The new H1 development boards have a different pinout, this is to support the new boards.

**Comment by alevy** [comment]
Ah! I'm happy with this then, maybe it's worth naming the boards with a version? e.g. `golfv1` `golfv2`? Just a thumbs up or thumbs down for this comment for whether you want to make this change. I don't particularly care. If not, I'll just merge

**Comment by zmbush** [comment]
I don't particularly care.

**Comment by domrizzo** [comment]
I think it's for a different version of the golf board, but otherwise
identical. Should it go elsewhere?

**Comment by domrizzo** [comment]
thumbs up

**Pull request merged**
